const roles = ["Por","Dc","B","Ds","Dd","E","M","C","W","T","A","Pc"];
const teams = ["IO","Zago","Mezza","Baso","Luca","Gian","Rav","Righetto"];
let players = [], purchases = [], selected;
const $ = selector => document.querySelector(selector);
const number = value => Number(String(value || 0).replace(",", ".")) || 0;

function purchaseFor(player) { return purchases.find(p => p.playerId === player.id); }
function renderTeams() { $('#teams').innerHTML = teams.map(team => { const roster = purchases.filter(p => p.buyer === team); const spent = roster.reduce((sum,p) => sum + p.credits,0); return `<article class="team"><div class="team-top"><span>${team}</span><span class="budget">● ${500-spent}</span></div><small>${roster.length} giocatori · ${spent} spesi</small><span class="team-players">${roster.map(p=>p.name).join(" · ") || "Rosa da costruire"}</span></article>`; }).join(''); }
function metric(label,value) { return `<span class="metric">${label}<b>${value || "–"}</b></span>`; }
function renderPlayers() { const query = $('#search').value.trim().toLowerCase(), role = $('#role').value, showSold = $('#sold').checked, [sort,keyOrder] = $('#sort').value.split('-'); let result = players.filter(p => (!role || p.Ruolo === role) && (showSold || !purchaseFor(p)) && (!query || `${p.Nome} ${p.Team}`.toLowerCase().includes(query))); result.sort((a,b) => { const aVal = sort === 'Nome' ? a.Nome : number(a[sort]), bVal = sort === 'Nome' ? b.Nome : number(b[sort]); return keyOrder === 'asc' ? String(aVal).localeCompare(String(bVal), 'it', {numeric:true}) : number(bVal)-number(aVal); }); const fragment = document.createDocumentFragment(), template = $('#player-template'); result.forEach(p => { const item = template.content.cloneNode(true); const article = item.querySelector('.player'), sold = purchaseFor(p); article.classList.toggle('sold',Boolean(sold)); item.querySelector('.role').textContent=p.Ruolo; item.querySelector('.name').textContent=p.Nome; item.querySelector('.club').textContent=p.Team; item.querySelector('.badges').innerHTML=[p['Obiett.']&&`<span class="badge goal">★ Obiettivo</span>`,p.Fascia&&`<span class="badge">${p.Fascia}</span>`].filter(Boolean).join(''); item.querySelector('.metrics').innerHTML=metric('Prezzo',p.Prezzo)+metric('PMA',p.PMA)+metric('Quo',p.Quo)+metric('FMV',p.FMV); const button=item.querySelector('.assign'); button.textContent=sold ? `${sold.buyer} · ${sold.credits}` : 'Assegna'; button.disabled=Boolean(sold); button.onclick=()=>openAssign(p); fragment.append(item); }); $('#players').replaceChildren(fragment); }
function renderSearchResult() { const query = $('#search').value.trim().toLowerCase(); const result = $('#search-result'); if (!query) return result.replaceChildren(); const hits=players.filter(p=>`${p.Nome} ${p.Team}`.toLowerCase().includes(query)).slice(0,4); result.innerHTML=hits.map(p=>`<div class="quick-result" data-id="${p.id}"><strong>${p.Nome} <span class="muted">${p.Ruolo} · ${p.Team}</span></strong><span class="muted">${p.Commento || p['Nota 1'] || 'Nessuna nota'}</span></div>`).join(''); result.querySelectorAll('[data-id]').forEach(el=>el.onclick=()=>openAssign(players.find(p=>p.id===el.dataset.id))); }
function openAssign(player) { if (purchaseFor(player)) return; selected=player; $('#modal-name').textContent=player.Nome; $('#modal-info').textContent=`${player.Ruolo} · ${player.Team} · Prezzo guida ${player.Prezzo || '–'} · ${player.Commento || pNotes(player) || 'nessuna nota'}`; $('#credits').value=player.Prezzo || ''; $('#assign-dialog').showModal(); }
function pNotes(p){return ['Nota 1','Nota 2','Nota 3','Nota 4','Nota 5'].map(k=>p[k]).filter(Boolean).join(' · ')}
async function load() { try { const [playersResponse,purchasesResponse] = await Promise.all([fetch('/api/players'),fetch('/api/purchases')]); const data=await playersResponse.json(), bought=await purchasesResponse.json(); if (!playersResponse.ok) throw new Error(data.error); players=data.players; purchases=bought.purchases || []; roles.forEach(role=>$('#role').insertAdjacentHTML('beforeend',`<option value="${role}">${role}</option>`)); teams.forEach(team=>$('#buyer').insertAdjacentHTML('beforeend',`<option>${team}</option>`)); renderTeams();renderPlayers(); } catch(error) { $('#players').innerHTML=`<p class="muted">${error.message}. Configura le variabili d'ambiente Vercel e riprova.</p>`; } }
$('#search').addEventListener('input',()=>{renderSearchResult();renderPlayers()}); $('#role').onchange=renderPlayers; $('#sort').onchange=renderPlayers; $('#sold').onchange=renderPlayers;
$('#assign-form').addEventListener('submit',async event=>{event.preventDefault(); const button=$('#confirm');button.disabled=true;button.textContent='Salvataggio…'; try { const response=await fetch('/api/purchases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({playerId:selected.id,name:selected.Nome,role:selected.Ruolo,team:selected.Team,buyer:$('#buyer').value,credits:number($('#credits').value)})}); const data=await response.json();if(!response.ok)throw new Error(data.error);purchases=await (await fetch('/api/purchases')).json().then(x=>x.purchases);$('#assign-dialog').close();renderTeams();renderPlayers(); }catch(error){alert(error.message)}finally{button.disabled=false;button.textContent='Conferma acquisto'}});
load();

