const roles=["Por","Dc","B","Ds","Dd","E","M","C","W","T","A","Pc"],teams=["IO","Zago","Mezza","Baso","Luca","Gian","Rav","Righetto"],stats=["Prezzo","PMA","Quo","MV","FMV","Presenze","Pt. Tit.","Gol","Ass","Amm","Esp","Rig. Segnati","Rig. Sbagliati","Gol Subiti","Rig. Parati"];
let players=[],purchases=[],selected,role="";const $=s=>document.querySelector(s),num=v=>Number(String(v||0).replace('%','').replace(',','.'))||0,purchase=p=>purchases.find(x=>x.playerId===p.id||(x.name===p.Nome&&x.team===p.Team));
function teamsView(){$('#teams').innerHTML=teams.map(t=>{let r=purchases.filter(p=>p.buyer===t),s=r.reduce((a,p)=>a+p.credits,0);return `<article class="team"><div class="team-top"><span>${t}</span><span class="budget">● ${500-s}</span></div><small>${r.length} giocatori · ${s} spesi</small><span class="team-players">${r.map(p=>p.name).join(' · ')||'Rosa da costruire'}</span></article>`}).join('')}
function card(p,off=false){let x=$('#player-template').content.cloneNode(true),b=x.querySelector('.assign');x.querySelector('.role').textContent=p.Ruolo;x.querySelector('.name').textContent=p.Nome;x.querySelector('.club').textContent=p.Team;x.querySelector('.badges').innerHTML=[p['Obiett.']&&'<span class="badge goal">★ Obiettivo</span>',p.Fascia&&`<span class="badge">${p.Fascia}</span>`].filter(Boolean).join('');x.querySelector('.metrics').innerHTML=stats.map(k=>`<span class="metric">${k}<b>${p[k]||'–'}</b></span>`).join('');b.textContent=off?'Rimetti disponibile':'Assegna';b.onclick=()=>off?undo(purchase(p)):assign(p);return x}
function list(){let q=$('#search').value.toLowerCase(),[key,dir]=$('#sort').value.split('|'),a=players.filter(p=>!purchase(p)&&(!role||p.roles?.includes(role)||p.Ruolo.includes(role))&&(`${p.Nome} ${p.Team}`.toLowerCase().includes(q)));a.sort((x,y)=>dir==='asc'?num(x[key])-num(y[key]):num(y[key])-num(x[key]));let f=document.createDocumentFragment();a.forEach(p=>f.append(card(p)));$('#players').replaceChildren(f)}
function unavailable(){let a=players.filter(p=>purchase(p)),f=document.createDocumentFragment();a.forEach(p=>f.append(card(p,true)));$('#unavailable').replaceChildren(f);$('#unavailable-count').textContent=`${a.length} acquistati`}
function search(){let q=$('#search').value.toLowerCase(),box=$('#search-result');if(!q)return box.replaceChildren();let p=players.find(x=>`${x.Nome} ${x.Team}`.toLowerCase().includes(q));if(!p)return box.innerHTML='<p class="muted">Nessun giocatore trovato.</p>';box.innerHTML=`<div class="search-detail"><div class="search-detail-top"><div><p class="eyebrow">SCHEDA GIOCATORE</p><h2>${p.Nome}</h2><p class="muted">${p.Ruolo} · ${p.Team}</p></div><button id="detail">${purchase(p)?'Già acquistato':'Assegna giocatore'}</button></div><div class="detail-grid">${Object.entries(p).filter(([k,v])=>v&&!['id','roles','roleSheet'].includes(k)).map(([k,v])=>`<span class="detail ${k==='Commento'||k.includes('Nota')?'note':''}">${k}<b>${v}</b></span>`).join('')}</div></div>`;let b=$('#detail');b.disabled=!!purchase(p);b.onclick=()=>assign(p)}
function assign(p){selected=p;$('#modal-name').textContent=p.Nome;$('#modal-info').textContent=`${p.Ruolo} · ${p.Team} · ${p.Commento||'nessuna nota'}`;$('#credits').value=p.Prezzo||'';$('#assign-dialog').showModal()}
async function refresh(){purchases=(await (await fetch('/api/purchases')).json()).purchases||[];teamsView();list();unavailable();search()}
async function undo(p){if(!confirm(`Rimettere ${p.name} tra i disponibili?`))return;await fetch('/api/purchases',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({playerId:p.playerId})});refresh()}
async function load(){let [a,b]=await Promise.all([fetch('/api/players'),fetch('/api/purchases')]),d=await a.json();players=d.players;purchases=(await b.json()).purchases||[];$('#role-buttons').innerHTML=`<button class="active" data-role="">Tutti</button>${roles.map(r=>`<button data-role="${r}">${r}</button>`).join('')}`;$('#role-buttons').onclick=e=>{let b=e.target.closest('[data-role]');if(!b)return;role=b.dataset.role;document.querySelectorAll('[data-role]').forEach(x=>x.classList.toggle('active',x===b));list()};$('#sort').innerHTML=stats.map(k=>`<option value="${k}|desc">${k}: alto → basso</option><option value="${k}|asc">${k}: basso → alto</option>`).join('');teams.forEach(t=>$('#buyer').insertAdjacentHTML('beforeend',`<option>${t}</option>`));teamsView();list();unavailable()}
$('#search').oninput=()=>{search();list()};$('#sort').onchange=list;$('#assign-form').onsubmit=async e=>{e.preventDefault();await fetch('/api/purchases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({playerId:selected.id,name:selected.Nome,role:selected.Ruolo,team:selected.Team,buyer:$('#buyer').value,credits:num($('#credits').value)})});$('#assign-dialog').close();refresh()};load();

